### ISSUE TITLE
Bringing chocolatey-oneget repo up to date

### ISSUE THREAD

**Issue by lholman** [chocolatey-community/chocolatey-oneget#3]
@ferventcoder As discussed in https://gitter.im/chocolatey/chocolatey-oneget on November 11th, here is an issue to track the work of bringing the changes that @Jaykul applied to the https://github.com/OneGet/ChocolateyProvider repo over here. 

For clarity, below is the approach I've taken (including just the first commit initially), could you confirm I've understood this please then I'll send the first PR over?
- Forked source: https://github.com/OneGet/ChocolateyProvider
- Forked target: https://github.com/chocolatey/chocolatey-oneget
- Found @Jaykul commits in source
  - Last common commit to both repos https://github.com/lholman/ChocolateyProvider/commit/d2dcb8f2c2ebf2d7ae5a434dd0330adb2f13b6ca
  - First commit to source that needs to be applied to target https://github.com/lholman/ChocolateyProvider/commit/04ea66f93c8f0ba23d0c81a3904304c50bad65e7
- Added a remote (source) to my target fork, fetched all commits from source

```
C:\Development\github\chocolatey-oneget [master]> git remote -v
chocolatey      https://github.com/chocolatey/chocolatey-oneget.git (fetch)
chocolatey      https://github.com/chocolatey/chocolatey-oneget.git (push)
origin  https://github.com/lholman/chocolatey-oneget.git (fetch)
origin  https://github.com/lholman/chocolatey-oneget.git (push)
source  C:/Development/github/ChocolateyProvider (fetch)
source  C:/Development/github/ChocolateyProvider (push)
C:\Development\github\chocolatey-oneget [master]> git fetch source
remote: Counting objects: 83, done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 66 (delta 42), reused 59 (delta 35)
Unpacking objects: 100% (66/66), done.
From C:/Development/github/ChocolateyProvider
 * [new branch]      master     -> source/master
C:\Development\github\chocolatey-oneget [master]> git status
On branch master
Your branch is up-to-date with 'origin/master'.
```
- Cherry picked the first commit 04ea66f93c8f0ba23d0c81a3904304c50bad65e7 from source and commited to target

```
C:\Development\github\chocolatey-oneget [master]> git cherry-pick 04ea66f93c8f0ba23d0c81a3904304c50bad65e7 --edit -x
```
- Built locally
- Pushed to target fork
- Created PR

**Comment by ferventcoder** [comment]
looks good. Go ahead with the PR.

**Comment by lholman** [comment]
@ferventcoder Code we re-open this issue and I'll reference it in the subsequent PR's until we're up to date?

**Comment by ferventcoder** [comment]
Sure

**Comment by ferventcoder** [comment]
@lholman is this good or still being worked on?

**Comment by lholman** [comment]
@ferventcoder More work to do, if you're happy to merge them in I can get the subsequent PR's over to you over the next week I imagine, does that work?

**Comment by ferventcoder** [comment]
You bet.

**Comment by ferventcoder** [comment]
This is now done.
